name: bugsnag_http_client
description: "BugSnag flutter http client wrapper."
version: 1.2.0
homepage: https://www.bugsnag.com/
documentation: https://docs.bugsnag.com/performance/flutter/
repository: https://github.com/bugsnag/bugsnag-flutter-http-client
issue_tracker: https://github.com/bugsnag/bugsnag-flutter-http-client/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  bugsnag_bridge:
    git: # TODO: Replace once bugsnag_bridge is published
      url: https://github.com/bugsnag/bugsnag-flutter-common
      ref: robert/bugsnag-flutter-bridge
      path: packages/bugsnag-flutter-bridge

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
